name: Deploy to Kinsta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.KINSTA_HOST }}
          port: ${{ secrets.KINSTA_PORT }}
          username: ${{ secrets.KINSTA_USER }}
          password: ${{ secrets.KINSTA_PASS }}
          protocol: ftps
          local-dir: ./wp-content/
          server-dir: /www/testmig_838/public/wp-content/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            uploads/**